auctionApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', include('auctions.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    re_path(r'static/(.+)', views._static_butler)
]

auctions/urls.py
from django.urls import path
from . import views

app_name = 'auctions'

urlpatterns = [
    path('', views.index, name='index'),
    path('auction', views.addAuction, name='addAuction'),
    path('auction/closed-auction', views.getClosedAuction, name='closedAuction'),
    path('auction/<int:id>/edit', views.editAuction, name='editAuction'),
    path('auction/<int:id>/', views.auctionIndex, name='auctionIndex'),
    path('auction/<int:id>/participant/add', views.addParticipant, name='addParticipant'),
    path('auction/<int:id>/participant/list', views.listParticipants, name='listParticipant'),
    path('auction/<int:aid>/participant/<int:pid>/edit', views.editParticipant, name='editParticipant'),
    path('auction/<int:aid>/participant/<int:pid>/delete', views.deleteParticipant, name='deleteParticipant'),
    path('auction/<int:id>/item/add', views.addItem, name='addItem'),
    path('auction/<int:aid>/item/<int:itemid>/edit', views.editItem, name='editItem'),
    path('auction/<int:aid>/item/<int:itemid>/bid', views.bidItem, name='bidItem'),
    path('auction/<int:aid>/item/<int:itemid>/bid-detail', views.getBidDetail, name='getBidDetail'),
    path('auction/<int:aid>/sold-items', views.getSoldItems, name='getSoldItems'),
    path('lot/time/<int:id>/', views.getBidClosingTime, name='getBidClosingTime'),
    path('select', views.getSelectHtml, name='getSelect'),
    path('notification', views.getNotification, name='notification'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('register', views.registerUser, name='register'),
    path('deregister', views.deregisterUser, name='deregister'),
    path('logout', views.logoutUser, name='logout')
]

auctions/models.py
from django.db import models
from django.utils import timezone



class Auction(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=200, default='opened')
    auction1 = models.CharField(max_length=200, default='0')
    maxparticipant = models.CharField(max_length=200, default='0')
    username = models.CharField(max_length=200, default='-')
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.description


class Item(models.Model):
    auctionid = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    categoryid = models.CharField(max_length=200)
    subcategoryid = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    minimumbid = models.IntegerField()
    username = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    createdat = models.DateTimeField(default=timezone.now)
    startat = models.DateTimeField(default=timezone.now)
    endat = models.DateTimeField()

    def __str__(self):
        return self.name
       

class Participant(models.Model):
    auctionid = models.CharField(max_length=200)
    userid = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.auctionid



class Bid(models.Model):
    auctionid = models.CharField(max_length=200)
    itemid = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    amount = models.IntegerField()
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.auctionid


class Notification(models.Model):
    auctionid = models.CharField(max_length=200)
    itemid = models.CharField(max_length=200)
    seller = models.CharField(max_length=200)
    winner = models.CharField(max_length=200)
    bid = models.CharField(max_length=200)
    status = models.CharField(max_length=100, default='pending')
    bidtime = models.DateTimeField(default=timezone.now)
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.auctionid
 


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    

class SubCategory(models.Model):
    categoryid = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    createdat = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

auctions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.messages import success, error
from django.http import HttpResponse
from time import strftime
from .utils import addNewItem, getAllRecords, hasBiddingClosed
from .utils import addNewBid, getBidTimeDiffInSecTupple, resetTimeForItemNotBidded
from .utils import handleBiddingClosure, getNotificationCount
from .utils import getNotificationList, getRecordByPk, getBidWinner, addNewAuction
from .utils import addNewParticipant, participantStatus, doEditAuction
from .utils import doEditparticipant, auctionStatus, doEditItem
from .models import Auction, Item, Bid, Category, SubCategory, Participant
from django.contrib.auth.models import User
import logging



# @login_required
def index(req):
    context = {
        'pageOptions':{
            'page':'index', 
            'buttonLabel':'View', 
            'header':'Active Auctions',
            'index': 'active-menu'
        }
    }
    try:
        filteredAuction = Auction.objects.filter(status='opened')
    except:
        logging.error('Index: Auctions not found')
        return render(req, 'auctions/index.html', context=context)
    else:
        context['auctions'] = filteredAuction
        return render(req, 'auctions/index.html', context=context)
    

@login_required
def addAuction(req):
    if req.method == 'POST':
        return addNewAuction(req)
    
    context = {
        'pageOptions':{
            'addAuction': 'active-menu'
        }
    }
    return render(req, 'auctions/addAuction.html', context=context)



@login_required
def editAuction(req, id):

    if req.method == 'POST':
        return doEditAuction(req, id)

    auction = getRecordByPk(Auction, id)
    context = {'auction':auction, 'auctionStatus':auctionStatus}
    return render(req, 'auctions/editAuction.html', context=context)


@login_required
def auctionIndex(req, id):
    auction = getRecordByPk(Auction, id)
    context = {
        'auction':auction, 
        'pageOptions':{
            'page':'auctionIndex', 
            'viewBtnLabel':'Bid', 
            'header':'Items On Auction',
            'buttonLabel': 'Bid'
        }
    }
    try:
        filteredItems = Item.objects.filter(auctionid=id, status='opened')
    except:
        logging.error('Index: items not found')
        return render(req, 'auctions/auctionIndex.html', context=context)
    else:
        context['items'] = filteredItems
        return render(req, 'auctions/auctionIndex.html', context=context)
    


@login_required
def addParticipant(req, id):
    
    if req.method == 'POST':
        return addNewParticipant(req, id)

    auction = getRecordByPk(Auction, id)
    context = {'auction':auction, 'participantStatus':participantStatus}
    return render(req, 'auctions/addParticipant.html', context=context)
    


@login_required
def listParticipants(req, id):
    auction = getRecordByPk(Auction, id)
    auctionContext = {'auction': auction}
    try:
        participants = Participant.objects.filter(auctionid=id, status__in=participantStatus)
    except Exception as e:
        logging.error(f'listParticipants: {e}')
        error(request=req, message='An error occured. Try again.')
        return render(req, 'auctions/listParticipant.html', context=auctionContext)
    else:
        canEdit = False
        if req.user.username.lower() == auction.username.lower():
            canEdit = True
        context = {'participants': participants, **auctionContext, 'canEdit':canEdit}
        return render(req, 'auctions/listParticipant.html', context=context)



@login_required
def editParticipant(req, aid, pid):
    participant = getRecordByPk(Participant, pid)
    auction = getRecordByPk(Auction, aid)

    if not auction or not participant:
        return index(req)

    if req.method == 'POST':
        return doEditparticipant(req, aid, pid)
    
    context = {'auction': auction, 'participant':participant, 'participantStatus':participantStatus}
    return render(req, 'auctions/editParticipant.html', context=context)



@login_required
def deleteParticipant(req, aid, pid):
    try:
        participant = Participant.objects.get(pk=pid)
    except:
        logging.error('doEditparticipant: Participant not found')
        return redirect('auctions:editParticipant', aid=aid ,pid=pid)
    else:
        participant.status = 'deleted'
        participant.save()
        return redirect('auctions:listParticipant', id=aid)



@login_required
def addItem(req, id):

    if req.method == 'POST':
        return addNewItem(req, id)
    
    auction = getRecordByPk(Auction, id)
    return render(req, 'auctions/addItem.html', context={'auction':auction})
    


@login_required
def editItem(req, aid, itemid):

    if req.method == 'POST':
        return doEditItem(req, aid, itemid)
    
    auction = getRecordByPk(Auction, aid)
    item = getRecordByPk(Item, itemid)
    username = req.user.username
    canEdit = False
    if item and (username.lower() == item.username.lower()):
        canEdit = True

    context = {
        'auction':auction,
        'item': item,
        'canEdit': canEdit
    }
    return render(req, 'auctions/editItem.html', context=context)
    


@login_required
def bidItem(req, aid, itemid):
    
    if req.method == 'POST':
      return addNewBid(req, aid, itemid)
    
    page = req.GET.get('page')
    triggers = {'index':'every 1s', 'soldItems':'load'}

    try:
        trigger = triggers[page]
    except Exception as e:
        logging.error(e)
        trigger = 'every 1s'


    bids = None
    auction = getRecordByPk(Auction, aid) 

    try:
        participants = Participant.objects.filter(auctionid=aid, status='active')
    except:
        participants = None


    try:
        bids = Bid.objects.filter(auctionid=auction.id)
    except:
        logging.error(f'Item does not exist')
        

    item = getRecordByPk(Item, itemid)

    context = {
        'auction': auction,
        'item': item, 
        'bids':bids, 
        'participants': participants,
        'pageOptions':{'trigger':trigger}
    }
    
    return render(req, 'auctions/bidItem.html', context=context)




def getBidClosingTime(req, id):
    
    handleBiddingClosure(id)

    if hasBiddingClosed(id):
        return HttpResponse('Bidding closed')
    
    resetTimeForItemNotBidded(id)

    bidTimeTupple = getBidTimeDiffInSecTupple(id)
    timeDiff = strftime('%M:%S', bidTimeTupple)
    return HttpResponse(timeDiff)
    


def getNotification(req):
    user = req.user.username
    if not user:
        logging.warning('User not logged in')
        return HttpResponse('')
    
    notificationType = req.GET.get('type')
    notificationType = notificationType.lower()

    if notificationType == 'count':
        notificationCount = getNotificationCount(user)
        return HttpResponse(notificationCount)
    
    notificationList = getNotificationList(user)
    return HttpResponse(notificationList)




def getBidDetail(req, aid, itemid):
    
    item = getRecordByPk(Item, itemid)

    if not item:
        return HttpResponse('')
    
    bids = Bid.objects.filter(itemid=item.id)

    bidList = "<ul>"
    for bid in bids:
        bidList += f"<li><span class='bid-date'>{bid.createdat.strftime('%Y-%m-%d %H:%M:%S')}</span> Competing bid ({bid.username}): <span class='bid-amount'>${bid.amount}</span><li>"
    bidList += '<ul>'
    winner = getBidWinner(itemid)
    if winner:
        bidList += f"<div id='bid-winner'>Winner: {winner}</div>"
    return HttpResponse(bidList)




def getSelectHtml(req):
    tableName = req.GET.get('target').lower()
    categoryId = req.GET.get('categoryid')
    modelOptions = {
        'category':{'model':Category, 'label':'name', 'filterKwargs':''}, 
        'subcategory':{'model':SubCategory, 'filterKwargs':{'categoryid':categoryId}, 'label':'name'}, 
        'user':{'model':User, 'filterKwargs':{'is_active':1}, 'label':'username'}
    } 

    if not tableName:
        logging.error('getSelectHtml: request query string empty')
        return HttpResponse(select)
    
    select = f"<option value=''>Select {tableName}</option>"
    modelOption = modelOptions[tableName]

    if not modelOption:
        logging.error(f'getSelectHtml: modelOption not found for {tableName}')
        return HttpResponse(select)
    
    model = modelOption['model']

    if not model:
        logging.error(f'getSelectHtml: model not found for {tableName}')
        return HttpResponse(select)
    
    filterKwargs = modelOption['filterKwargs']

    if filterKwargs:
        records = model.objects.filter(**filterKwargs)
    else:
        records = getAllRecords(model)

    if not records:
        logging.error(f'getSelectHtml: record not found for {tableName}')
        return HttpResponse(select)
    
    label = modelOption['label']

    for record in records:
        select += f"<option value='{record.id}'>"
        select += getattr(record, label)
        select += '</option>'

    return HttpResponse(select)



def getSoldItems(req, aid):
    context = {'pageOptions':{'page':'soldItems', 'buttonLabel':'View', 'header':'Sold Items'}}
    auction = getRecordByPk(Auction, aid)
    try:
        filteredItems = Item.objects.filter(auctionid=aid, status='closed')
    except:
        logging.error('getSoldItems: items not found')
        return render(req, 'auctions/auctionIndex.html', context=context)
    else:
        context['auction'] = auction
        context['items'] = filteredItems
        return render(req, 'auctions/auctionIndex.html', context=context)
    


def getClosedAuction(req):
    context = {
        'pageOptions':{
            'page':'index', 
            'buttonLabel':'View', 
            'header':'Closed Auctions',
            'index': 'active-menu'
        }
    }
    try:
        filteredAuction = Auction.objects.filter(status='closed')
    except:

templates/auctions/addAuction.html
{% extends "base.html" %}


{% block content %}

<div class="addContact container_main">
  <div class="registration form">
    <header>Add Auction</header>
    <form action="{% url 'auctions:addAuction' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="auction-flex">
        <input type="text" required name="name" placeholder="Auction Name">
        <input type="number" required name="maxparticipant" placeholder="Maximum participant">
        <input type="text" required name="description" placeholder="Description">
      </div>

      {% include "auctions/message.html" %}

      <button type="submit" class="button">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

templates/auctions/addItem.html
{% extends "auctions/auctionBase.html" %}

{% block auction_content %}

<div hx-get="{% url 'auctions:getSelect' %}?target=category" hx-trigger="load" hx-target="#category"></div>

<div class="addContact container_main">
  <div class="registration form">
    <header>Add Item</header>
    <form action="{% url 'auctions:addItem' auction.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-flex">
        <input type="text" required name="name" placeholder="Item Name">
        <input type="text" required name="description" placeholder="Description">
        <select name="categoryid" id="category" hx-get="{% url 'auctions:getSelect' %}?target=subcategory"
          hx-target="#subcategory">
        </select>
        <select name="subcategoryid" id="subcategory">
          <option value="">Sub-Category</option>
        </select>
        <input type="number" required name="minimumbid" placeholder="Starting Price">
        <input type="file" required name="image" placeholder="Upload Image">
      </div>
      <button type="submit" class="button">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

templates/auctions/addParticipant.html
{% extends "auctions/auctionBase.html" %}



{% block auction_content %}

<div
  hx-get="{% url 'auctions:getSelect' %}?target=user"
  hx-trigger="load"
  hx-target="#participant"
></div>

<div class="addContact container_main">
  <div class="registration form">
    <header>Add Participant</header>
    <form hx-post="{% url 'auctions:addParticipant' auction.id %}" hx-target=".participant-msg" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="edit-auction-flex">
        <label for="username" class="auction-flex-item">Username</label>
        <select name="username" id="participant" required></select>
        {% if participantStatus %}
        <label for="status" class="auction-flex-item">Status</label>
        <select name="status" id="status">
          {% for status in participantStatus %}
            <option value="{{status}}">{{status}}</option>
          {% endfor %}
        </select>
        {% endif %}
      </div>
      <div class="participant-msg success"></div>
      <button type="submit" class="button">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

templates/auctions/auction.html
{% extends "base.html" %}



{% block content %}
<section class="section__container product__container" id="product">
    {% include "auctions/message.html" %}
    {% if items and pageOptions %}
    <h4 class="section__header">{{pageOptions.header}}</h4>
    <div class="product__grid">
        {% for item in items %}
        <div class="product__card">
            <h4>{{item.name}}</h4>
            <!-- <p>item.minimumbid</p> -->
            <p>Started: {{item.createdat}}</p>
            <p>Lot No.: <strong>{{item.id}}</strong></p>
            <div class="product-status">Status: <strong>{{item.status}}</strong></div>
            <div class="btn-div">
                <a class="bid-btn" href="{% url 'auctions:bidItem' item.id %}?page={{pageOptions.page}}">
                    {{pageOptions.buttonLabel}}
                </a>
            </div>
            <img src="{{item.image}}" alt="{{item.name}}" />
        </div>
        {% endfor %}
        {% else %}
    </div>
    <div class="auction-notice">No item available</div>
    {% endif %}
</section>
{% endblock %}

templates/auctions/auctionBase.html
{% extends "base.html" %}



{% block content %}
<section class="section__container product__container" id="product">
    {% if auction %}
    <div class="auctionbase__header">
        <a href="{% url 'auctions:auctionIndex' auction.id %}">
            <h3>{{auction.name}}</h3>
            <span>Maximum Participant: <strong>{{auction.maxparticipant}}</strong></span>
            <span>Status: <strong>{{auction.status}}</strong></span>
            <span>Created By: <strong>{{auction.username}}</strong></span>
        </a>
    </div>
    <nav>
        <ul class="nav__links auction__nav__links" id="nav-links">
                {% with current_url=request.get_full_path %}
                    {% url 'auctions:auctionIndex' auction.id as url %}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">Live Auction</a>
                    </li>
                    {% url 'auctions:editAuction' auction.id as url %}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">Edit Auction</a>
                    </li>
                    {% url 'auctions:addParticipant' auction.id as url %}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">Add Participant</a>
                    </li>
                    {% url 'auctions:listParticipant' auction.id as url %}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">List participant</a>
                    </li>
                    {% url 'auctions:addItem' auction.id as url%}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">Add Item</a>
                    </li>
                    {% url 'auctions:getSoldItems' auction.id as url %}
                    <li class="{% if current_url == url %} active-menu {%endif%}">
                        <a href="{{ url }}">Sold Items</a>
                    </li>
                {% endwith %}
        </ul>
    </nav>
    {% include "auctions/message.html" %}
    {% block auction_content %}{% endblock %}

    {% else %}
        <div class="auction-notice">Auction not found</div>
    {% endif %}

</section>
{% endblock %}

templates/auctions/auctionIndex.html
{% extends "auctions/auctionBase.html" %}



{% block auction_content %}
<div>
    {% if pageOptions %}
    <h4 class="section__header">{{pageOptions.header}}</h4>
    {% if auction and items %}
    <div class="product__grid">
        {% for item in items %}
        <div class="product__card">
            <h4>{{item.name}}</h4>
            <p>Started: {{item.createdat}}</p>
            <p>Lot No.: <strong>{{item.id}}</strong></p>
            <div class="product-status">Status: <strong>{{item.status}}</strong></div>
            <div class="item-flex">
                {% if pageOptions.page == 'auctionIndex' %}
                <div class="btn-div_">
                    <a class="bid-btn" href="{% url 'auctions:editItem' auction.id item.id %}?page={{pageOptions.page}}">
                        Edit
                    </a>
                </div>
                {% endif %}
                <div class="btn-div_">
                    <a class="bid-btn" href="{% url 'auctions:bidItem' auction.id item.id %}?page={{pageOptions.page}}">
                        {{pageOptions.buttonLabel}}
                    </a>
                </div>
            </div>
            <img src="{{item.image}}" alt="{{item.name}}" />
        </div>
        {% endfor %}
    </div>
    {% else %}
        <div class="auction-notice">No item found</div>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/auctions/bidItem.html
{% extends "auctions/auctionBase.html" %}

{% block auction_content %}
<div class="biditem-container">
  <section class="section__container product__container" id="product">
    <div class="biditem-grid">

      <div class="product__card biditem-participants">
        <div class="biditem-participants-header">Participants</div>
        {% if participants %}
        {% for participant in participants %}
        <ul id="{{participant.id}}" class="biditem-participants-list">
          <li class="participant__name">{{participant.username}}</li>
        </ul>
        {% endfor %}
        {% else %}
        <div class="auction-notice">No active participant found</div>
        {% endif %}
      </div>

      {% if item %}
      <div class="product__card biditem-item">
        <h4>{{item.name}}</h4>
        <img src="{{item.image}}" alt="{{item.name}}" />
        <div class="biditem-p" id="close-in">
          Closes in: <span id="bid-time" hx-get="{% url 'auctions:getBidClosingTime' item.id %}"
            hx-trigger="{{pageOptions.trigger}}" hx-target="#bid-time"></span>
        </div>
        <p>Seller: <strong>{{item.username}}</strong></p>
        <p>Lot No.: <strong>{{item.id}}</strong></p>
        <p>Starting Price: <strong>${{item.minimumbid}}</strong></p>
        <p>Start Date: <strong>{{item.createdat}}</strong></p>
        <p>Description: {{item.description}}</p>
      </div>
      {% endif %}

      <div class="bid-info product__card" id="bid-info">
        <div class="bid-list" hx-get="{% url 'auctions:getBidDetail' auction.id item.id %}"
          hx-trigger="{{pageOptions.trigger}}" hx-target=".bid-list"></div>
        {% if item.status != 'closed' %}
        <form class="bid-detail" hx-post="{% url 'auctions:bidItem' auction.id item.id %}" hx-target="#bid-response">
          {% csrf_token %}
          <input class="input" required name="amount" type="number">
          <input class="hidden" name="username" value="{{item.username}}">
          <input class="hidden" name="minimumbid" value="{{item.minimumbid}}">
          <button type="submit" class="btn">Bid</button>
        </form>
        <div id="bid-response" class="display-nonez"></div>
        {% endif %}
      </div>

    </div>
  </section>
</div>
{% endblock %}

templates/auctions/editAuction.html
{% extends "auctions/auctionBase.html" %}


{% block auction_content %}

<div class="addContact container_main">
  <div class="registration form">
    <header>Edit Auction</header>
    <form action="{% url 'auctions:editAuction' auction.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="edit-auction-flex">
          <label for="name" class="auction-flex-item">Auction name</label>
          <input class="auction-flex-item_" type="text" required name="name" value="{{auction.name}}">
          <label class="auction-flex-item" for="maxparticipant">Max Participants</label>
          <input class="auction-flex-item_" type="number" required name="maxparticipant" value="{{auction.maxparticipant}}">
          <label class="auction-flex-item" for="description">Description</label>
          <input class="auction-flex-item_" type="text" required name="description" value="{{auction.description}}">
        {% if auctionStatus %}
          <label class="auction-flex-item" for="status">Status</label>
          <select class="auction-flex-item_" name="status" id="status">
            {% for status in auctionStatus %}
              {% if auction.status == status %}
                <option value="{{status}}" selected>{{status}}</option>
              {% else %}
                <option value="{{status}}">{{status}}</option>
              {% endif %}
            {% endfor %}
          </select>
        {% endif %}
      </div>
      <button type="submit" class="button">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

templates/auctions/editItem.html
{% extends "auctions/auctionBase.html" %}

{% block auction_content %}

<div class="addContact container_main">
  <div class="registration form">
    <header>Edit Item</header>
    {% if canEdit %}
    <form action="{% url 'auctions:editItem' auction.id item.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="edit-auction-flex">
        <label for="name" class="auction-flex-item">Name</label>
        <input type="text" required name="name" value="{{item.name}}">
        <label for="description" class="auction-flex-item">Description</label>
        <input type="text" required name="description" value="{{item.description}}">
        <label for="minimumbid" class="auction-flex-item">Starting Price</label>
        <input type="number" required name="minimumbid" value="{{item.minimumbid}}">
      </div>
      <button type="submit" class="button">Submit</button>
    </form>
    {% else %}
    <div class="auction-notice">You don't have the permission to edit this item</div>
    {% endif %}
  </div>
</div>


{% endblock %}

templates/auctions/editParticipant.html
{% extends "auctions/auctionBase.html" %}



{% block auction_content %}

<div class="addContact container_main">
  <div class="registration form">
    <header>Edit Participant</header>
    <form action="{% url 'auctions:editParticipant' auction.id participant.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="edit-auction-flex">
        <label for="username" class="auction-flex-item">Username</label>
        <input name="username" disabled id="participant" value="{{ participant.username }}"></input>
        {% if participantStatus %}
        <label for="status" class="auction-flex-item">Status</label>
        <select name="status" id="status">
          {% for status in participantStatus %}
            {% if participant.status == status %}
              <option value="{{status}}" selected>{{status}}</option>
            {% else %}
              <option value="{{status}}">{{status}}</option>
            {% endif %}
          {% endfor %}
        </select>
        {% endif %}
      </div>
      <div class="participant-msg success"></div>
      <button type="submit" class="button">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

templates/auctions/index.html
{% extends "base.html" %}



{% block content %}
<section class="section__container product__container" id="product">
    {% include "auctions/message.html" %}
    {% if pageOptions %}
    <h4 class="section__header">{{pageOptions.header}}</h4>
    {% if auctions %}
    <div class="product__grid">
        {% for auction in auctions %}
        <div class="product__card">
            <div class="auction__btn">
                <div class="btn-div">
                    <a class="bid-btn" href="{% url 'auctions:auctionIndex' auction.id %}?page={{pageOptions.page}}">
                        {{pageOptions.buttonLabel}}
                    </a>
                </div>
            </div>
            <h3>{{auction.name}}</h3>
            <p>Started: {{auction.createdat}}</p>
            <p>Max Participants: <strong>{{auction.maxparticipant}}</strong></p>
            <div class="product-status">Status: <strong>{{auction.status}}</strong></div>
            <p>Description: {{auction.description}}</p>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="auction-notice">No {{pageOptions.header}} available</div>
    {% endif %}
    {% endif %}
</section>
{% endblock %}

templates/auctions/listParticipant.html
{% extends "auctions/auctionBase.html" %}



{% block auction_content %}
<div class="participant__main">
  <div class="participant">
    <header>
      <h1 class="participant__title">
        <span class="participant__title--top">{{auction.name}}</span>
        <span class="participant__title--bottom">participants</span>
      </h1>
    </header>

    <main class="participant__profiles">
      {% if participants %}
        {% for participant in participants %}
          <article id="{{participant.id}}" class="participant__profile">
            <span class="participant__name">{{participant.username}}</span>
            <span class="participant__value">{{participant.status}}</span>
            {% if canEdit %}
            <span><a class="participant__edit" href="{% url 'auctions:editParticipant' auction.id participant.id %}">edit</a></span>
            <span><a class="participant__delete" url="{% url 'auctions:deleteParticipant' auction.id participant.id %}">delete</a></span>
            {% endif %}
          </article>
        {% endfor %}
      {% else %}
        <div class="auction-notice">No active participant found</div>
      {% endif %}
    </main>
  </div>
</div>

{% endblock %}