auctionApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', include('auctions.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    re_path(r'static/(.+)', views._static_butler)
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('register', views.registerUser, name='register'),
    path('deregister', views.deregisterUser, name='deregister'),
    path('logout', views.logoutUser, name='logout')
]

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>Login</title>
</head>

<body>
  <div class="container">
    <div class="login form">
      <header>Login</header>
      <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" required name="username" placeholder="Enter your username">
        <input type="password" required name="password" placeholder="Enter your password">
        <div>
          {% include "auctions/message.html" %}
        </div>
        <button type="submit" class="button">Login</button>
      </form>
      <div class="signup">
        <span class="signup">Don't have an account?
          <a href="{% url 'users:register' %}" for="signup">Signup</a>
        </span>
      </div>
    </div>
  </div>
</body>

</html>

templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>Register</title>
</head>

<body>
  <div class="container">
    <div class="registration form">
      <header>Signup</header>
      <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <input type="text" required name="first_name" placeholder="Enter your first name">
        <input type="text" required name="last_name" placeholder="Enter your last name">
        <input type="text" required name="username" placeholder="Enter your username">
        <input type="text" required name="email" placeholder="Enter your email">
        <input type="password" required name="password1" placeholder="Create a password">
        <input type="password" required name="password2" placeholder="Confirm your password">
        <div>
          {% include "auctions/message.html" %}
        </div>
        <button type="submit" class="button">Signup</button>
      </form>
      <div class="signup">
        <span class="signup">Already have an account?
          <a href="{% url 'users:login' %}" for="signup">Login</a>
        </span>
      </div>
    </div>
  </div>
</body>

</html>